// Auto-generated by scripts/generate-static-slugs.mjs — do not edit manually
export const BUILD_TIME_CAR_SLUGS: readonly string[] = [
  "honda-city-10-turbo-sv-2022",
  "honda-civic-2020-turbo",
  "honda-jazz-2019",
  "isuzu-dmax-2020-z",
  "mazda-2-13-high-connect-2019",
  "nissan-navara-2019-calibre",
  "toyota-camry-2019-hybrid",
  "toyota-fortuner-2018-diesel",
  "toyota-hilux-2018-revo",
  "toyota-vios-15-entry-2021",
  "toyota-vios-2021"
];

export function isStaticCarSlug(slug: string): boolean {
  return BUILD_TIME_CAR_SLUGS.includes(slug);
}
